### PR TITLE
helm-mt supports multi-vterm.

### PR DESCRIPTION
**Pull request by hackartists**
* Default terminal mode was modified to `vterm`
* `term` and `shell` modes were still supported.

### CODE REVIEW

**Comment by dfdeshom** [comment]
Hello,
thanks for the pull request. I would not make multi-vterm the default terminal mode since the package focuses on managing terms mainly. Also, I don't see `multi-vterm` listed as a dependency in the pull request.

**Comment by hackartists** [comment]
@dfdeshom Firstly, thank you for your response and understand your interests. But, I would like to ask you why this repository just focus on managing terms. 
As I know, `term` and `shell` mode are running on emacs, while `vterm` is running with external C library.
In fact, I also did not notice the difference in performance. But I would say that it is undeniable that `vterm` has better performance.

**Comment by dfdeshom** [comment]
> But, I would like to ask you why this repository just focus on managing terms.

This library was written before `vterm` was written, that's the reason it's focused on `term` mode. 

> But I would say that it is undeniable that vterm has better performance.

I don't dispute that `vterm` is faster, my 2 issues are:
* `vterm` is not a dependency, which means that someone installing `heml-mt` will probably have to install `vterm` separately and thus end up with a broken `helm-mt` install
* `vterm` is the default which in my view breaks with the curent behavior, which is focused on managing `term` mode shells

**Comment by hackartists** [comment]
Thank you for your response. I will close this PR.
Anyway, I enjoyed productive conversation with you.

**Pull request closed without merging**
